import type { Address } from 'viem';
import { base, ink, type SupportedChainId } from '@basepress/chain';

// Contract address per chain. Filled in after deploy.
// New chain? Deploy BasePress.sol there + add an entry here.
export const CONTRACT_ADDRESSES: Record<SupportedChainId, Address | null> = {
  [base.id]: null, // TODO: deploy V2 to Base
  [ink.id]: null,  // TODO: deploy V2 to Ink
};

export function getContractAddress(chainId: number): Address | null {
  return (CONTRACT_ADDRESSES as Record<number, Address | null>)[chainId] ?? null;
}

// Off-chain API base. Same domain across chains — articles are chain-agnostic.
export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://api.basepress.app';

// ===== EIP-712 typed data shape for off-chain article permits =====
// Author signs once per article; the permit is stored on the API and replayed
// by readers when they call mintWithPermit on whichever chain they choose.

export const PERMIT_DOMAIN_NAME = 'BasePress';
export const PERMIT_DOMAIN_VERSION = '1';

export const MINT_PERMIT_TYPES = {
  MintPermit: [
    { name: 'articleId', type: 'bytes32' },     // sha256 of articleSlug + nonce, off-chain identifier
    { name: 'contentURI', type: 'string' },     // R2 URL or ipfs:// later
    { name: 'author', type: 'address' },        // revenue split target
    { name: 'price', type: 'uint256' },         // per-mint price in wei
    { name: 'maxSupply', type: 'uint256' },     // 0 = unlimited
    { name: 'deadline', type: 'uint256' },      // unix seconds
  ],
} as const;

// ===== V2 contract ABI (subset) — only the reader-facing functions =====
// Full ABI generated by hardhat lives at contracts/artifacts after compile.
export const BASEPRESS_ABI = [
  {
    name: 'mintWithPermit',
    type: 'function',
    stateMutability: 'payable',
    inputs: [
      {
        name: 'permit',
        type: 'tuple',
        components: [
          { name: 'articleId', type: 'bytes32' },
          { name: 'contentURI', type: 'string' },
          { name: 'author', type: 'address' },
          { name: 'price', type: 'uint256' },
          { name: 'maxSupply', type: 'uint256' },
          { name: 'deadline', type: 'uint256' },
        ],
      },
      { name: 'signature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    name: 'articleSupply',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'articleId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'platformSigner',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'platformFeeBps',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const;
