import type { Address } from 'viem';
import { base, ink, type SupportedChainId } from '@basepress/chain';

// Contract address per chain. Filled in after deploy.
// New chain? Deploy BasePress.sol there + add an entry here.
export const CONTRACT_ADDRESSES: Record<SupportedChainId, Address | null> = {
  [base.id]: '0xAdf3d339B1030ac84fa56430C6a86455fBCEA5cd', // V2 deployed 2026-04-28
  [ink.id]: '0xcaf3D13E55fc7c62c1fea07dcD3FbA0D682080Ab',  // V2 deployed 2026-04-28
};

export function getContractAddress(chainId: number): Address | null {
  return (CONTRACT_ADDRESSES as Record<number, Address | null>)[chainId] ?? null;
}

// Off-chain API base. Same domain across chains — articles are chain-agnostic.
export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://api.basepress.app';

// ===== EIP-712 typed data shape for off-chain article permits =====
// Author signs once per article; the permit is stored on the API and replayed
// by readers when they call mintWithPermit on whichever chain they choose.

export const PERMIT_DOMAIN_NAME = 'BasePress';
export const PERMIT_DOMAIN_VERSION = '1';

export const MINT_PERMIT_TYPES = {
  MintPermit: [
    { name: 'articleId', type: 'bytes32' },     // sha256 of articleSlug + nonce, off-chain identifier
    { name: 'author', type: 'address' },        // revenue split target
    { name: 'deadline', type: 'uint256' },      // unix seconds; 0 = no expiry
  ],
} as const;

// V4: fixed mint price hardcoded in contract (no permit field needed)
export const MINT_PRICE = 0.001; // ether — matches contract constant

// ===== V4 contract ABI (subset) — reader + withdraw surface =====
// Full ABI generated by hardhat lives at contracts/artifacts after compile.
export const BASEPRESS_ABI = [
  {
    name: 'mintWithPermit',
    type: 'function',
    stateMutability: 'payable',
    inputs: [
      {
        name: 'permit',
        type: 'tuple',
        components: [
          { name: 'articleId', type: 'bytes32' },
          { name: 'author', type: 'address' },
          { name: 'deadline', type: 'uint256' },
        ],
      },
      { name: 'signature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    name: 'articleSupply',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'articleId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'platformSigner',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'platformFeeBps',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'authorBalances',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'platformBalance',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'platformTreasury',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'owner',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'id', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'withdrawAuthor',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'withdrawPlatform',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
] as const;
